name: "Example Workflow"

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: "A String input to demonstrate passing a parameter into a workflow"
        required: true

jobs:
  TestJob:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo ${{ github.event.inputs.my_input }}
    


